/// Token types produced by the SQL tokenizer.

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    // Literals
    Integer(i64),
    Float(f64),
    String(String),
    Blob(Vec<u8>),

    // Identifiers
    Ident(String),

    // Keywords
    Keyword(Keyword),

    // Operators and punctuation
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Eq,
    NotEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    LeftParen,
    RightParen,
    Comma,
    Semicolon,
    Dot,
    Pipe, // ||  (string concat)

    // End of input
    Eof,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Keyword {
    Select,
    From,
    Where,
    And,
    Or,
    Not,
    Insert,
    Into,
    Values,
    Update,
    Set,
    Delete,
    Create,
    Drop,
    Table,
    Index,
    On,
    If,
    Exists,
    Primary,
    Key,
    Autoincrement,
    Null,
    Integer,
    Text,
    Real,
    Blob,
    As,
    Is,
    In,
    Between,
    Like,
    Order,
    By,
    Asc,
    Desc,
    Limit,
    Offset,
    Count,
    Sum,
    Avg,
    Min,
    Max,
    Begin,
    Commit,
    Rollback,
    Transaction,
    Default,
    Unique,
    Check,
    Group,
    Having,
    Join,
    Inner,
    Cross,
    Left,
    Right,
    Outer,
}

impl Keyword {
    pub fn from_str(s: &str) -> Option<Keyword> {
        match s.to_uppercase().as_str() {
            "SELECT" => Some(Keyword::Select),
            "FROM" => Some(Keyword::From),
            "WHERE" => Some(Keyword::Where),
            "AND" => Some(Keyword::And),
            "OR" => Some(Keyword::Or),
            "NOT" => Some(Keyword::Not),
            "INSERT" => Some(Keyword::Insert),
            "INTO" => Some(Keyword::Into),
            "VALUES" => Some(Keyword::Values),
            "UPDATE" => Some(Keyword::Update),
            "SET" => Some(Keyword::Set),
            "DELETE" => Some(Keyword::Delete),
            "CREATE" => Some(Keyword::Create),
            "DROP" => Some(Keyword::Drop),
            "TABLE" => Some(Keyword::Table),
            "INDEX" => Some(Keyword::Index),
            "ON" => Some(Keyword::On),
            "IF" => Some(Keyword::If),
            "EXISTS" => Some(Keyword::Exists),
            "PRIMARY" => Some(Keyword::Primary),
            "KEY" => Some(Keyword::Key),
            "AUTOINCREMENT" => Some(Keyword::Autoincrement),
            "NULL" => Some(Keyword::Null),
            "INTEGER" => Some(Keyword::Integer),
            "TEXT" => Some(Keyword::Text),
            "REAL" => Some(Keyword::Real),
            "BLOB" => Some(Keyword::Blob),
            "AS" => Some(Keyword::As),
            "IS" => Some(Keyword::Is),
            "IN" => Some(Keyword::In),
            "BETWEEN" => Some(Keyword::Between),
            "LIKE" => Some(Keyword::Like),
            "ORDER" => Some(Keyword::Order),
            "BY" => Some(Keyword::By),
            "ASC" => Some(Keyword::Asc),
            "DESC" => Some(Keyword::Desc),
            "LIMIT" => Some(Keyword::Limit),
            "OFFSET" => Some(Keyword::Offset),
            "COUNT" => Some(Keyword::Count),
            "SUM" => Some(Keyword::Sum),
            "AVG" => Some(Keyword::Avg),
            "MIN" => Some(Keyword::Min),
            "MAX" => Some(Keyword::Max),
            "BEGIN" => Some(Keyword::Begin),
            "COMMIT" => Some(Keyword::Commit),
            "ROLLBACK" => Some(Keyword::Rollback),
            "TRANSACTION" => Some(Keyword::Transaction),
            "DEFAULT" => Some(Keyword::Default),
            "UNIQUE" => Some(Keyword::Unique),
            "CHECK" => Some(Keyword::Check),
            "GROUP" => Some(Keyword::Group),
            "HAVING" => Some(Keyword::Having),
            "JOIN" => Some(Keyword::Join),
            "INNER" => Some(Keyword::Inner),
            "CROSS" => Some(Keyword::Cross),
            "LEFT" => Some(Keyword::Left),
            "RIGHT" => Some(Keyword::Right),
            "OUTER" => Some(Keyword::Outer),
            _ => None,
        }
    }
}
